modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "millionhorses"
version = "${version}"
displayName = "1 Million Horses"
authors = "Traincrafter111!"
description = '''
A Java port of the amazing 1 Million Horses addon for bedrock by Cynosia
'''
#logoFile = ""

[[dependencies.millionhorses]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.millionhorses]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.millionhorses]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.millionhorses]]
modId = "azurelib"
mandatory = true
versionRange = "[1.3.2,)"
ordering = "AFTER"
side = "BOTH"